[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Esteban Acevedo", email = "esteban.horacio.acevedo@gmail.com"},
]
dependencies = []
requires-python = ">=3.11"
license = {text = "MIT"}
